# frontend/Dockerfile
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine

# Copiar el build de React
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar nuestra configuración mágica de Nginx (AÑADE ESTA LÍNEA)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]