server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Esta es la línea mágica que arregla el 404:
        try_files $uri $uri/ /index.html;
    }

    # Opcional pero recomendado: Evitar errores 404 con archivos estáticos
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}